### ISSUE TITLE
OK so IDK if this is an issue that everyone has but if it is thats even better and hopefully will get fixed soon. Whenever I switch servers with solarstats on, it gives me an error message and shuts down the server.

### ISSUE THREAD

**Issue by Husk-ees** [Solar-Tweaks/SolarStats#25]
/Users/(me)/SolarStats/node_modules/@solar-tweaks/minecraft-protocol-lunarclient/src/LCPlayer.js:56
 ––––   this.waypoints.forEach((waypoint) => {
                   ^

TypeError: Cannot read properties of undefined (reading 'forEach')
–––– at LCPlayer.removeAllWaypoints (/Users/(me)/SolarStats/node_modules/@solar-tweaks/minecraft-protocol-lunarclient/src/LCPlayer.js:56:20)
 ––––   at Listener.<anonymous> (/Users/(me)/SolarStats/build/player/Player.js:60:27)
 ––––   at Listener.emit (node:events:527:28)
 ––––   at InstantConnectProxy.<anonymous> (/Users/(me)/SolarStats/build/Classes/Listener.js:11:22)
 ––––   at InstantConnectProxy.emit (node:events:539:35)
 ––––   at Client.<anonymous> (/Users/(me)/SolarStats/node_modules/prismarine-proxy/src/instant_connect_proxy.js:50:12)
 ––––   at Client.emit (node:events:527:28)
 ––––  at FullPacketParser.<anonymous> (/Users/(me)/SolarStats/node_modules/minecraft-protocol/src/client.js:91:12)
 ––––   at FullPacketParser.emit (node:events:527:28)
 ––––   at addChunk (/Users/(me)/SolarStats/node_modules/readable-stream/lib/_stream_readable.js:298:12)

**Comment by TBHGodPro** [comment]
open terminal, go to the solar stats directory, and type:

git pull;npm install;npm update
