### ISSUE TITLE
hypixel crashes after playing game and now i can't open solarstats.hypixel.net:25556

### ISSUE THREAD

**Issue by mjc087** [Solar-Tweaks/SolarStats#28]
<img width="1012" alt="Screen Shot 2022-07-22 at 2 28 05 PM" src="https://user-images.githubusercontent.com/109779857/180369204-99a5c615-5df2-4316-84ca-1bd8b2d40156.png">
help pls
<img width="658" alt="Screen Shot 2022-07-22 at 8 50 20 PM" src="https://user-images.githubusercontent.com/109779857/180433539-ab5ca999-0db4-4e78-b7bd-51ba23bfcfcb.png">
also this

**Comment by Husk-ees** [comment]
Same same same same problem ples we need help

**Comment by TBHGodPro** [comment]
both of you open terminal, go to the solar stats directory, and type:

`git pull;npm install;npm update`

**Comment by Husk-ees** [comment]
Thanks it works perfectly now!

**Comment by mjc087** [comment]
I realized that it works perfectly now but the bedwars waypoints and notification doesn't work for me. Also the bedwars teammates doesn't work. Only mvp++ and location update thing works.
